### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by markus-s24** [neuroph/master#16]
Some dependencies (e.g. android:android) cannot be resolved via maven central. And there is no documentation where to get them from. This way it is very difficult to build neuroph via maven.

Furthermore at least some tests fail if executed via maven, e.g. GaussianTest.

**Comment by neuroph** [comment]
Use our maven repository at http://neuroph.sourceforge.net/maven2/
We're working on tests at the moment

**Comment by markus-s24** [comment]
Thanks, I overlooked that.
